//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanRibickogKluba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClanRibickogKluba()
        {
            this.ZahtjevZaPrijavuNatjecanjaClanas = new HashSet<ZahtjevZaPrijavuNatjecanjaClana>();
        }
    
        public int id_clana { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int OIB { get; set; }
        public string email { get; set; }
        public string mjesto_rodenja { get; set; }
        public System.DateTime datum_rodenja { get; set; }
        public System.DateTime datum_upisa { get; set; }
        public string drzavljanstvo { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
        public int ribicki_klub { get; set; }
        public int administrator { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual RibickiKlub RibickiKlub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtjevZaPrijavuNatjecanjaClana> ZahtjevZaPrijavuNatjecanjaClanas { get; set; }
    }
}
