//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishingNetEntities : DbContext
    {
        public FishingNetEntities()
            : base("name=FishingNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClanRibickogKluba> ClanRibickogKlubas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Lokacija> Lokacijas { get; set; }
        public virtual DbSet<Natjecanje> Natjecanjes { get; set; }
        public virtual DbSet<RibickiKlub> RibickiKlubs { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<SudionikNatjecanja> SudionikNatjecanjas { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
        public virtual DbSet<ZahtjevZaPrijavuNatjecanjaClana> ZahtjevZaPrijavuNatjecanjaClanas { get; set; }
        public virtual DbSet<ZahtjevZaPrijavuNatjecanjaExterni> ZahtjevZaPrijavuNatjecanjaExternis { get; set; }
        public virtual DbSet<PrijavljeniKorisnik> PrijavljeniKorisniks { get; set; }
    }
}
