//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.ClanRibickogKlubas = new HashSet<ClanRibickogKluba>();
            this.Lokacijas = new HashSet<Lokacija>();
            this.Natjecanjes = new HashSet<Natjecanje>();
            this.ZahtjevZaPrijavuNatjecanjaExternis = new HashSet<ZahtjevZaPrijavuNatjecanjaExterni>();
            this.ZahtjevZaPrijavuNatjecanjaClanas = new HashSet<ZahtjevZaPrijavuNatjecanjaClana>();
        }
    
        public int id_korisnika { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string email { get; set; }
        public System.DateTime datum_vrijeme_registracije { get; set; }
        public int uloga_id_uloga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanRibickogKluba> ClanRibickogKlubas { get; set; }
        public virtual Uloga Uloga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lokacija> Lokacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Natjecanje> Natjecanjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtjevZaPrijavuNatjecanjaExterni> ZahtjevZaPrijavuNatjecanjaExternis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtjevZaPrijavuNatjecanjaClana> ZahtjevZaPrijavuNatjecanjaClanas { get; set; }
    }
}
