//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Natjecanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Natjecanje()
        {
            this.SudionikNatjecanjas = new HashSet<SudionikNatjecanja>();
            this.ZahtjevZaPrijavuNatjecanjaExternis = new HashSet<ZahtjevZaPrijavuNatjecanjaExterni>();
            this.ZahtjevZaPrijavuNatjecanjaClanas = new HashSet<ZahtjevZaPrijavuNatjecanjaClana>();
        }
    
        public int id_natjecanje { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> datum_pocetka { get; set; }
        public Nullable<System.DateTime> datum_zavrsetka { get; set; }
        public int lokacija { get; set; }
        public int moderator { get; set; }
        public Nullable<int> pobjednik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Lokacija Lokacija1 { get; set; }
        public virtual SudionikNatjecanja SudionikNatjecanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SudionikNatjecanja> SudionikNatjecanjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtjevZaPrijavuNatjecanjaExterni> ZahtjevZaPrijavuNatjecanjaExternis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtjevZaPrijavuNatjecanjaClana> ZahtjevZaPrijavuNatjecanjaClanas { get; set; }
    }
}
