//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class RibickiKlub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RibickiKlub()
        {
            this.ClanRibickogKlubas = new HashSet<ClanRibickogKluba>();
        }
    
        public int id_ribicki_klub { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string predsjednik { get; set; }
        public string email { get; set; }
        public string web_adresa { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public string telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanRibickogKluba> ClanRibickogKlubas { get; set; }
    }
}
