//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SudionikNatjecanja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SudionikNatjecanja()
        {
            this.Natjecanjes = new HashSet<Natjecanje>();
        }
    
        public int id_sudionika { get; set; }
        public int natjecanje { get; set; }
        public Nullable<int> prijava_clan { get; set; }
        public Nullable<int> prijava_eksterni { get; set; }
        public int bodovi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Natjecanje> Natjecanjes { get; set; }
        public virtual Natjecanje Natjecanje1 { get; set; }
        public virtual ZahtjevZaPrijavuNatjecanjaClana ZahtjevZaPrijavuNatjecanjaClana { get; set; }
        public virtual ZahtjevZaPrijavuNatjecanjaExterni ZahtjevZaPrijavuNatjecanjaExterni { get; set; }
    }
}
