//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZahtjevZaPrijavuNatjecanjaExterni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZahtjevZaPrijavuNatjecanjaExterni()
        {
            this.SudionikNatjecanjas = new HashSet<SudionikNatjecanja>();
        }
    
        public int id_eksterni { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int OIB { get; set; }
        public string email { get; set; }
        public string mjesto_rodenja { get; set; }
        public System.DateTime datum_rodenja { get; set; }
        public string drzavljanstvo { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
        public string opis_prijave { get; set; }
        public System.DateTime datum_prijave { get; set; }
        public Nullable<int> odobreno { get; set; }
        public int natjecanje { get; set; }
        public int moderator { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Natjecanje Natjecanje1 { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SudionikNatjecanja> SudionikNatjecanjas { get; set; }
    }
}
